### ISSUE TITLE
avoid divide by zero 

### ISSUE THREAD

**Issue by XieHuoHuo** [FaspDevTeam/faspsolver#2]
when I run a fasp-amg-program, I face "divide by zero" error in PreAMGAggregationUA.inl -> form_pairwise().

I found it's caused by variable "temp4". After adding code below, program works fine now:

            // avoid temp4 to be zero
            if ( ABS(temp4) < SMALLREAL ) 
                temp4 = (temp4>0)? SMALLREAL:-SMALLREAL;

**Comment by zhangcs** [comment]
Fixed now. Thanks!
